# https://github.com/microsoft/dotnet-podcasts/blob/main/.github/workflows/podcast-dotnet-maui-ci.yml
name: .NET MAUI CI

on:
  push:
    branches: [ "main", "develop", /^release\-.*$/ ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main", "develop", /^release\-.*$/ ] 
    paths-ignore:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-mobile:
    uses: ./.github/workflows/template-dotnet-maui-ci.yml
    with:
      csproj: MauiGithubSearch/MauiGithubSearch.csproj
